-- Active: 1727878930875@@127.0.0.1@3306@deaddraw
DROP SCHEMA IF EXISTS DeadDraw;
CREATE SCHEMA DeadDraw;
USE DeadDraw; 


/* DROP SCHEMA IF EXISTS DeadDraw_DB_wheneveram;
CREATE SCHEMA DeadDraw_DB_wheneveram;
USE DeadDraw_DB_wheneveram; */

CREATE TABLE Player(
    idPlayer INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) UNIQUE,
    baseHealth INT NOT NULL DEFAULT 20,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    registrationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    baseTime INT NOT NULL DEFAULT 100,
    money INT NOT NULL DEFAULT 0,
    role VARCHAR(255) NOT NULL DEFAULT 'player',
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




CREATE TABLE Logbook (
    idLogbook INT AUTO_INCREMENT PRIMARY KEY,
    idPlayer INT NOT NULL,
    connectionTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    disconnectionTime TIMESTAMP,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idPlayer) REFERENCES Player(idPlayer)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Deck (
    idDeck INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE Table MatchGame(
    idMatchGame INT AUTO_INCREMENT PRIMARY KEY,
    idPlayer INT NOT NULL,
    idDeck INT NOT NULL,
    score INT NOT NULL,
    result ENUM('victory', 'defeat', 'in progress') NOT NULL DEFAULT 'in progress',
    startDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    endDate TIMESTAMP NULL,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Foreign Key (idPlayer) REFERENCES Player(idPlayer),
    Foreign Key (idDeck) REFERENCES Deck(idDeck)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE Lootbox(
    idLootbox INT AUTO_INCREMENT PRIMARY KEY,
    cost INT NOT NULL,
    quality TINYINT NOT NULL,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE Table PlayerLootbox(
    idPlayer INT NOT NULL,
    idLootbox INT NOT NULL,
    openingDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idPlayer) REFERENCES Player(idPlayer),
    FOREIGN KEY (idLootbox) REFERENCES Lootbox(idLootbox)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Card(
    idCard INT AUTO_INCREMENT PRIMARY KEY,
    value INT NOT NULL,
    suit ENUM('CardEnemie', 'CardEspada', 'CardVida') NOT NULL,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CardInDeck(
    idCard INT NOT NULL,
    idDeck INT NOT NULL,
    addedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idCard) REFERENCES Card(idCard),
    FOREIGN KEY (idDeck) REFERENCES Deck(idDeck)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE Table Effect(
    idEffect INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    type ENUM('attack', 'defense', 'healing') NOT NULL,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE RewardUpgrade(
    idEffect INT NOT NULL,
    quality TINYINT NOT NULL,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idEffect) REFERENCES Effect(idEffect)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE RewardCard (
    idCard INT NOT NULL,
    quality TINYINT NOT NULL,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idCard) REFERENCES Card(idCard)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CardEffect (
    idCard INT NOT NULL,
    idEffect INT NOT NULL,
    applicationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idCard) REFERENCES Card(idCard),
    FOREIGN KEY (idEffect) REFERENCES Effect(idEffect)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

update Player set username = 'hola' where idPlayer = 1;