-- Active: 1776136239786@@cc7mri.h.filess.io@3307@DeadDraw_DB_wheneveram
DROP SCHEMA IF EXISTS DeadDraw;
CREATE SCHEMA DeadDraw;
USE DeadDraw; 


/* DROP SCHEMA IF EXISTS DeadDraw_DB_wheneveram;
CREATE SCHEMA DeadDraw_DB_wheneveram;
USE DeadDraw_DB_wheneveram; */

CREATE TABLE Jugador(
    idJugador INT PRIMARY KEY AUTO_INCREMENT,
    vidaBase INT NOT NULL DEFAULT 20,
    correo VARCHAR(255) NOT NULL,
    contrasena VARCHAR(255) NOT NULL,
    fechaRegistro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tiempoBase INT NOT NULL DEFAULT 100,
    dinero INT NOT NULL DEFAULT 0,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




CREATE TABLE Bitacora (
    idBitacora INT AUTO_INCREMENT PRIMARY KEY,
    idJugador INT NOT NULL,
    horaConexion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    horaDesconexion TIMESTAMP NOT NULL,
    duracionSesion INT NOT NULL,
    activo BOOLEAN NOT NULL,
    tiempoActividad INT NOT NULL,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idJugador) REFERENCES Jugador(idJugador)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Baraja (
    idBaraja INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE Table Partida(
    idPartida INT AUTO_INCREMENT PRIMARY KEY,
    idJugador INT NOT NULL,
    puntaje INT NOT NULL,
    resultado ENUM('victoria', 'derrota', 'en progreso') NOT NULL DEFAULT 'en progreso',
    fechaInicio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fechaFin TIMESTAMP NULL,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Foreign Key (idJugador) REFERENCES Jugador(idJugador)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE Table JugadorBaraja(
    idJugador INT NOT NULL,
    idBaraja INT NOT NULL,
    vecesUsada INT NOT NULL DEFAULT 0,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idJugador) REFERENCES Jugador(idJugador),
    FOREIGN KEY (idBaraja) REFERENCES Baraja(idBaraja)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Lootbox(
    idLootbox INT AUTO_INCREMENT PRIMARY KEY,
    costo INT NOT NULL,
    calidad TINYINT NOT NULL,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE Table JugadorLootbox(
    idJugador INT NOT NULL,
    idLootbox INT NOT NULL,
    fechaApertura TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idJugador) REFERENCES Jugador(idJugador),
    FOREIGN KEY (idLootbox) REFERENCES Lootbox(idLootbox)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Carta(
    idCarta INT AUTO_INCREMENT PRIMARY KEY,
    costo INT NOT NULL,
    valor INT NOT NULL,
    palo ENUM('corazones', 'diamantes', 'treboles', 'picas') NOT NULL,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CartaEnBaraja(
    idCarta INT NOT NULL,
    idBaraja INT NOT NULL,
    fechaAgregado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idCarta) REFERENCES Carta(idCarta),
    FOREIGN KEY (idBaraja) REFERENCES Baraja(idBaraja)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE Table Efecto(
    idEfecto INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    tipo ENUM('ataque', 'defensa', 'curacion') NOT NULL,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE MejoraPremio(
    idEfecto INT NOT NULL,
    calidad TINYINT NOT NULL,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idEfecto) REFERENCES Efecto(idEfecto)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE CartaPremio (
    idCarta INT NOT NULL,
    calidad TINYINT NOT NULL,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idCarta) REFERENCES Carta(idCarta)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CartaEfecto (
    idCarta INT NOT NULL,
    idEfecto INT NOT NULL,
    fechaAplicacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idCarta) REFERENCES Carta(idCarta),
    FOREIGN KEY (idEfecto) REFERENCES Efecto(idEfecto)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;